name: flutter_mqtt_riverpod
description: Prototype Evergreen Registrar
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  amplify_auth_cognito: ^0.3.2
  amplify_authenticator: ^0.1.0-rc.5
  amplify_flutter: ^0.3.2
  aws_iot_api: ^1.2.0
  aws_iot_data_api: ^1.2.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
