name: flutter_mqtt_riverpod
description: Prototype Evergreen Registrar
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  amplify_api: ^0.4.1
  amplify_auth_cognito: ^0.4.0
  amplify_authenticator: 0.1.0-rc.6
  amplify_datastore: ^0.4.0
  amplify_flutter: ^0.4.0
  aws_greengrass_api: ^1.2.0
  aws_iot_api: ^1.2.0
  aws_iot_data_api: ^1.2.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  go_router: ^3.0.1
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  progress_indicators: ^1.0.0
  wifi_iot: ^0.3.15
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
